#!/bin/sh

mkdir -p web
rm web/* 
mogrify  -define jpeg -resize 1280x768 -auto-orient -unsharp 0x.5 -path web  *.jpg

mkdir -p th
rm th/* 
mogrify  -define jpeg:size=500x180 -auto-orient  -thumbnail 250x90 -unsharp 0x.5 -path th  *.jpg *.JPG

