#!/bin/sh

mkdir -p web
rm web/* 
mogrify  -define jpeg -resize 1280x768 -auto-orient -unsharp 0x.5 -path web  *.jpg *.JPG

mkdir -p th
rm th/* 
mogrify -auto-orient  -thumbnail 100x67 -gravity center -extent 100x67 -path th  *.jpg *.JPG
